[INPUT]
    Name              tail
    Path              /var/log/myapp/*.json
    Tag               app.json
    Parser            app_json
    Read_from_Head    true
    DB                /var/lib/fluent-bit/app.db

[FILTER]
    Name              modify
    Match             app.json
    Add               tags app.json

[OUTPUT]
    Name              http
    Match             app.json
    Host              data-prepper
    Port              2021
    URI               /log/ingest
    Format            json
