[INPUT]
    Name              tail
    Path              /var/log/auth.log
    Tag               linux.auth
    Read_from_Head    true
    DB                /var/lib/fluent-bit/auth.db

[FILTER]
    Name              modify
    Match             linux.auth
    Add               tags linux.auth
    Add               source_path /var/log/auth.log

[OUTPUT]
    Name              http
    Match             linux.auth
    Host              data-prepper
    Port              2021
    URI               /log/ingest
    Format            json
