[INPUT]
    Name              syslog
    Mode              udp
    Listen            0.0.0.0
    Port              1514
    Tag               linux.syslog

[FILTER]
    Name              modify
    Match             linux.syslog
    Add               tags linux.syslog

[OUTPUT]
    Name              http
    Match             linux.syslog
    Host              data-prepper
    Port              2021
    URI               /log/ingest
    Format            json
