[INPUT]
    Name              syslog
    Mode              udp
    Listen            0.0.0.0
    Port              5140
    Tag               network.firewall

[FILTER]
    Name              modify
    Match             network.firewall
    Add               tags network.firewall

[OUTPUT]
    Name              http
    Match             network.firewall
    Host              data-prepper
    Port              2021
    URI               /log/ingest
    Format            json
